# Voluntary financial support for NetVantage development.
# These links appear on the GitHub "Sponsor" button.
#
# NetVantage is free for personal/home use forever.
# Financial support is voluntary and does not unlock additional features.

github: HerbHall
ko_fi: herbhall
buy_me_a_coffee: herbhall
