version: 2

project_name: subnetree

before:
  hooks:
    - go mod tidy

builds:
  - id: subnetree
    main: ./cmd/subnetree/
    binary: subnetree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/HerbHall/subnetree/internal/version.Version={{.Version}}
      - -X github.com/HerbHall/subnetree/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/HerbHall/subnetree/internal/version.BuildDate={{.Date}}

  - id: scout
    main: ./cmd/scout/
    binary: scout
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/HerbHall/subnetree/internal/version.Version={{.Version}}
      - -X github.com/HerbHall/subnetree/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/HerbHall/subnetree/internal/version.BuildDate={{.Date}}

archives:
  - id: subnetree
    ids:
      - subnetree
    name_template: >-
      subnetree_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: scout
    ids:
      - scout
    name_template: >-
      scout_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: deploy/scout/scout.service
      - src: deploy/scout/install.sh
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: scout-binary
    ids:
      - scout
    name_template: "scout_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^chore\(deps\):'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Other
      order: 999

dockers:
  - id: subnetree-amd64
    ids:
      - subnetree
    goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/herbhall/subnetree:{{ .Tag }}-amd64"
      - "ghcr.io/herbhall/subnetree:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=SubNetree"
      - "--label=org.opencontainers.image.description=Network monitoring"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/HerbHall/subnetree"
      - "--label=org.opencontainers.image.licenses=BSL-1.1"
    dockerfile: Dockerfile.goreleaser

  - id: subnetree-arm64
    ids:
      - subnetree
    goos: linux
    goarch: arm64
    use: buildx
    image_templates:
      - "ghcr.io/herbhall/subnetree:{{ .Tag }}-arm64"
      - "ghcr.io/herbhall/subnetree:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=SubNetree"
      - "--label=org.opencontainers.image.description=Network monitoring"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/HerbHall/subnetree"
      - "--label=org.opencontainers.image.licenses=BSL-1.1"
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/herbhall/subnetree:{{ .Tag }}"
    image_templates:
      - "ghcr.io/herbhall/subnetree:{{ .Tag }}-amd64"
      - "ghcr.io/herbhall/subnetree:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/herbhall/subnetree:latest"
    image_templates:
      - "ghcr.io/herbhall/subnetree:latest-amd64"
      - "ghcr.io/herbhall/subnetree:latest-arm64"

sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"

release:
  github:
    owner: HerbHall
    name: subnetree
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## SubNetree {{.Version}}

    ### Installation

    **Docker (recommended):**
    ```
    docker run -d -p 8080:8080 -v subnetree-data:/data --cap-add NET_RAW --cap-add NET_ADMIN ghcr.io/herbhall/subnetree:{{ .Tag }}
    ```

    **Binary:** Download the appropriate archive for your platform below.
  footer: |
    ---
    Licensed under BSL 1.1 (core) and Apache 2.0 (plugin SDK).
