version: 2

project_name: netvantage

before:
  hooks:
    - go mod tidy

builds:
  - id: netvantage
    main: ./cmd/netvantage/
    binary: netvantage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/HerbHall/netvantage/internal/version.Version={{.Version}}
      - -X github.com/HerbHall/netvantage/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/HerbHall/netvantage/internal/version.BuildDate={{.Date}}

  - id: scout
    main: ./cmd/scout/
    binary: scout
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/HerbHall/netvantage/internal/version.Version={{.Version}}
      - -X github.com/HerbHall/netvantage/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/HerbHall/netvantage/internal/version.BuildDate={{.Date}}

archives:
  - id: netvantage
    ids:
      - netvantage
    name_template: >-
      netvantage_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: scout
    ids:
      - scout
    name_template: >-
      scout_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^chore\(deps\):'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Other
      order: 999

dockers:
  - id: netvantage-amd64
    ids:
      - netvantage
    goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/herbhall/netvantage:{{ .Tag }}-amd64"
      - "ghcr.io/herbhall/netvantage:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=NetVantage"
      - "--label=org.opencontainers.image.description=Network monitoring"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/HerbHall/netvantage"
      - "--label=org.opencontainers.image.licenses=BSL-1.1"
    dockerfile: Dockerfile.goreleaser

  - id: netvantage-arm64
    ids:
      - netvantage
    goos: linux
    goarch: arm64
    use: buildx
    image_templates:
      - "ghcr.io/herbhall/netvantage:{{ .Tag }}-arm64"
      - "ghcr.io/herbhall/netvantage:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=NetVantage"
      - "--label=org.opencontainers.image.description=Network monitoring"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/HerbHall/netvantage"
      - "--label=org.opencontainers.image.licenses=BSL-1.1"
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/herbhall/netvantage:{{ .Tag }}"
    image_templates:
      - "ghcr.io/herbhall/netvantage:{{ .Tag }}-amd64"
      - "ghcr.io/herbhall/netvantage:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/herbhall/netvantage:latest"
    image_templates:
      - "ghcr.io/herbhall/netvantage:latest-amd64"
      - "ghcr.io/herbhall/netvantage:latest-arm64"

sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - "--yes"
      - "--output-signature=${signature}"
      - "${artifact}"

release:
  github:
    owner: HerbHall
    name: netvantage
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## NetVantage {{.Version}}

    ### Installation

    **Docker (recommended):**
    ```bash
    docker run -d -p 8080:8080 \
      -v netvantage-data:/data \
      ghcr.io/herbhall/netvantage:{{ .Tag }}
    ```

    **Binary:** Download the appropriate archive for your platform below.

    See the [full changelog](https://github.com/HerbHall/netvantage/compare/{{.PreviousTag}}...{{.Tag}}) for all changes.
  footer: |
    **Full Changelog**: https://github.com/HerbHall/netvantage/compare/{{.PreviousTag}}...{{.Tag}}

    ---
    Licensed under BSL 1.1 (core) and Apache 2.0 (plugin SDK).
