// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: api/proto/v1/scout.proto

package scoutpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScoutService_CheckIn_FullMethodName       = "/subnetree.v1.ScoutService/CheckIn"
	ScoutService_ReportMetrics_FullMethodName = "/subnetree.v1.ScoutService/ReportMetrics"
	ScoutService_CommandStream_FullMethodName = "/subnetree.v1.ScoutService/CommandStream"
	ScoutService_ReportProfile_FullMethodName = "/subnetree.v1.ScoutService/ReportProfile"
)

// ScoutServiceClient is the client API for ScoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScoutService defines the communication between Scout agents and the SubNetree server.
type ScoutServiceClient interface {
	// CheckIn sends a periodic heartbeat from agent to server.
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	// ReportMetrics streams system metrics from agent to server.
	ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsReport, Ack], error)
	// CommandStream establishes a bidirectional stream for server-to-agent commands.
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, Command], error)
	// ReportProfile sends a full system profile snapshot from agent to server.
	ReportProfile(ctx context.Context, in *ProfileReport, opts ...grpc.CallOption) (*Ack, error)
}

type scoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoutServiceClient(cc grpc.ClientConnInterface) ScoutServiceClient {
	return &scoutServiceClient{cc}
}

func (c *scoutServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, ScoutService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoutServiceClient) ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsReport, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScoutService_ServiceDesc.Streams[0], ScoutService_ReportMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsReport, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoutService_ReportMetricsClient = grpc.ClientStreamingClient[MetricsReport, Ack]

func (c *scoutServiceClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScoutService_ServiceDesc.Streams[1], ScoutService_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandResponse, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoutService_CommandStreamClient = grpc.BidiStreamingClient[CommandResponse, Command]

func (c *scoutServiceClient) ReportProfile(ctx context.Context, in *ProfileReport, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ScoutService_ReportProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoutServiceServer is the server API for ScoutService service.
// All implementations must embed UnimplementedScoutServiceServer
// for forward compatibility.
//
// ScoutService defines the communication between Scout agents and the SubNetree server.
type ScoutServiceServer interface {
	// CheckIn sends a periodic heartbeat from agent to server.
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	// ReportMetrics streams system metrics from agent to server.
	ReportMetrics(grpc.ClientStreamingServer[MetricsReport, Ack]) error
	// CommandStream establishes a bidirectional stream for server-to-agent commands.
	CommandStream(grpc.BidiStreamingServer[CommandResponse, Command]) error
	// ReportProfile sends a full system profile snapshot from agent to server.
	ReportProfile(context.Context, *ProfileReport) (*Ack, error)
	mustEmbedUnimplementedScoutServiceServer()
}

// UnimplementedScoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoutServiceServer struct{}

func (UnimplementedScoutServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedScoutServiceServer) ReportMetrics(grpc.ClientStreamingServer[MetricsReport, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedScoutServiceServer) CommandStream(grpc.BidiStreamingServer[CommandResponse, Command]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedScoutServiceServer) ReportProfile(context.Context, *ProfileReport) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProfile not implemented")
}
func (UnimplementedScoutServiceServer) mustEmbedUnimplementedScoutServiceServer() {}
func (UnimplementedScoutServiceServer) testEmbeddedByValue()                      {}

// UnsafeScoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoutServiceServer will
// result in compilation errors.
type UnsafeScoutServiceServer interface {
	mustEmbedUnimplementedScoutServiceServer()
}

func RegisterScoutServiceServer(s grpc.ServiceRegistrar, srv ScoutServiceServer) {
	// If the following call panics, it indicates UnimplementedScoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoutService_ServiceDesc, srv)
}

func _ScoutService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoutService_ReportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScoutServiceServer).ReportMetrics(&grpc.GenericServerStream[MetricsReport, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoutService_ReportMetricsServer = grpc.ClientStreamingServer[MetricsReport, Ack]

func _ScoutService_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScoutServiceServer).CommandStream(&grpc.GenericServerStream[CommandResponse, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoutService_CommandStreamServer = grpc.BidiStreamingServer[CommandResponse, Command]

func _ScoutService_ReportProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoutServiceServer).ReportProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoutService_ReportProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoutServiceServer).ReportProfile(ctx, req.(*ProfileReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoutService_ServiceDesc is the grpc.ServiceDesc for ScoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subnetree.v1.ScoutService",
	HandlerType: (*ScoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _ScoutService_CheckIn_Handler,
		},
		{
			MethodName: "ReportProfile",
			Handler:    _ScoutService_ReportProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportMetrics",
			Handler:       _ScoutService_ReportMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CommandStream",
			Handler:       _ScoutService_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/scout.proto",
}
