// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: api/proto/v1/scout.proto

package scoutpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VersionStatus indicates the server's assessment of an agent's version.
type VersionStatus int32

const (
	VersionStatus_VERSION_OK               VersionStatus = 0
	VersionStatus_VERSION_DEPRECATED       VersionStatus = 1
	VersionStatus_VERSION_REJECTED         VersionStatus = 2
	VersionStatus_VERSION_UPDATE_AVAILABLE VersionStatus = 3
)

// Enum value maps for VersionStatus.
var (
	VersionStatus_name = map[int32]string{
		0: "VERSION_OK",
		1: "VERSION_DEPRECATED",
		2: "VERSION_REJECTED",
		3: "VERSION_UPDATE_AVAILABLE",
	}
	VersionStatus_value = map[string]int32{
		"VERSION_OK":               0,
		"VERSION_DEPRECATED":       1,
		"VERSION_REJECTED":         2,
		"VERSION_UPDATE_AVAILABLE": 3,
	}
)

func (x VersionStatus) Enum() *VersionStatus {
	p := new(VersionStatus)
	*p = x
	return p
}

func (x VersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_scout_proto_enumTypes[0].Descriptor()
}

func (VersionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_scout_proto_enumTypes[0]
}

func (x VersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionStatus.Descriptor instead.
func (VersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{0}
}

type CheckInRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform           string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AgentVersion       string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Metrics            *SystemMetrics         `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ProtoVersion       uint32                 `protobuf:"varint,6,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	EnrollToken        string                 `protobuf:"bytes,7,opt,name=enroll_token,json=enrollToken,proto3" json:"enroll_token,omitempty"`
	CertificateRequest []byte                 `protobuf:"bytes,8,opt,name=certificate_request,json=certificateRequest,proto3" json:"certificate_request,omitempty"` // DER-encoded PKCS#10 CSR (sent during enrollment/renewal)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CheckInRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CheckInRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CheckInRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *CheckInRequest) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CheckInRequest) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *CheckInRequest) GetEnrollToken() string {
	if x != nil {
		return x.EnrollToken
	}
	return ""
}

func (x *CheckInRequest) GetCertificateRequest() []byte {
	if x != nil {
		return x.CertificateRequest
	}
	return nil
}

type CheckInResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged         bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,2,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"`
	PendingCommands      []string               `protobuf:"bytes,3,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	VersionStatus        VersionStatus          `protobuf:"varint,4,opt,name=version_status,json=versionStatus,proto3,enum=subnetree.v1.VersionStatus" json:"version_status,omitempty"`
	ServerVersion        string                 `protobuf:"bytes,5,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UpgradeMessage       string                 `protobuf:"bytes,6,opt,name=upgrade_message,json=upgradeMessage,proto3" json:"upgrade_message,omitempty"`
	AssignedAgentId      string                 `protobuf:"bytes,7,opt,name=assigned_agent_id,json=assignedAgentId,proto3" json:"assigned_agent_id,omitempty"`
	SignedCertificate    []byte                 `protobuf:"bytes,8,opt,name=signed_certificate,json=signedCertificate,proto3" json:"signed_certificate,omitempty"` // DER-encoded X.509 certificate (returned after CSR signing)
	CaCertificate        []byte                 `protobuf:"bytes,9,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`             // DER-encoded CA root certificate (agent needs for TLS verification)
	UpdateUrl            string                 `protobuf:"bytes,10,opt,name=update_url,json=updateUrl,proto3" json:"update_url,omitempty"`                        // Download URL for agent binary when update is available
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *CheckInResponse) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

func (x *CheckInResponse) GetPendingCommands() []string {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

func (x *CheckInResponse) GetVersionStatus() VersionStatus {
	if x != nil {
		return x.VersionStatus
	}
	return VersionStatus_VERSION_OK
}

func (x *CheckInResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *CheckInResponse) GetUpgradeMessage() string {
	if x != nil {
		return x.UpgradeMessage
	}
	return ""
}

func (x *CheckInResponse) GetAssignedAgentId() string {
	if x != nil {
		return x.AssignedAgentId
	}
	return ""
}

func (x *CheckInResponse) GetSignedCertificate() []byte {
	if x != nil {
		return x.SignedCertificate
	}
	return nil
}

func (x *CheckInResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *CheckInResponse) GetUpdateUrl() string {
	if x != nil {
		return x.UpdateUrl
	}
	return ""
}

type SystemMetrics struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	CpuPercent       float64                 `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent    float64                 `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryUsedBytes  float64                 `protobuf:"fixed64,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes float64                 `protobuf:"fixed64,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	Disks            []*DiskMetric           `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks         []*NetworkMetric        `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	ContainerStats   []*DockerContainerStats `protobuf:"bytes,7,rep,name=container_stats,json=containerStats,proto3" json:"container_stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsedBytes() float64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotalBytes() float64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetDisks() []*DiskMetric {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemMetrics) GetNetworks() []*NetworkMetric {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SystemMetrics) GetContainerStats() []*DockerContainerStats {
	if x != nil {
		return x.ContainerStats
	}
	return nil
}

type DiskMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	TotalBytes    float64                `protobuf:"fixed64,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     float64                `protobuf:"fixed64,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     float64                `protobuf:"fixed64,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetric) Reset() {
	*x = DiskMetric{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetric) ProtoMessage() {}

func (x *DiskMetric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetric.ProtoReflect.Descriptor instead.
func (*DiskMetric) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{3}
}

func (x *DiskMetric) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetric) GetTotalBytes() float64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetric) GetUsedBytes() float64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetric) GetFreeBytes() float64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type NetworkMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	BytesSent     float64                `protobuf:"fixed64,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     float64                `protobuf:"fixed64,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetric) Reset() {
	*x = NetworkMetric{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetric) ProtoMessage() {}

func (x *NetworkMetric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetric.ProtoReflect.Descriptor instead.
func (*NetworkMetric) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkMetric) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkMetric) GetBytesSent() float64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetric) GetBytesRecv() float64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

type DockerContainerStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsageBytes uint64                 `protobuf:"varint,4,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryLimitBytes uint64                 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	MemoryPercent    float64                `protobuf:"fixed64,6,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetworkRxBytes   uint64                 `protobuf:"varint,7,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes   uint64                 `protobuf:"varint,8,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	BlockReadBytes   uint64                 `protobuf:"varint,9,opt,name=block_read_bytes,json=blockReadBytes,proto3" json:"block_read_bytes,omitempty"`
	BlockWriteBytes  uint64                 `protobuf:"varint,10,opt,name=block_write_bytes,json=blockWriteBytes,proto3" json:"block_write_bytes,omitempty"`
	Pids             uint32                 `protobuf:"varint,11,opt,name=pids,proto3" json:"pids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DockerContainerStats) Reset() {
	*x = DockerContainerStats{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerContainerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerContainerStats) ProtoMessage() {}

func (x *DockerContainerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerContainerStats.ProtoReflect.Descriptor instead.
func (*DockerContainerStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{5}
}

func (x *DockerContainerStats) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DockerContainerStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerContainerStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *DockerContainerStats) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *DockerContainerStats) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *DockerContainerStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *DockerContainerStats) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *DockerContainerStats) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *DockerContainerStats) GetBlockReadBytes() uint64 {
	if x != nil {
		return x.BlockReadBytes
	}
	return 0
}

func (x *DockerContainerStats) GetBlockWriteBytes() uint64 {
	if x != nil {
		return x.BlockWriteBytes
	}
	return 0
}

func (x *DockerContainerStats) GetPids() uint32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{9}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProfileReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Profile       *SystemProfile         `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReport) Reset() {
	*x = ProfileReport{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReport) ProtoMessage() {}

func (x *ProfileReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReport.ProtoReflect.Descriptor instead.
func (*ProfileReport) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{10}
}

func (x *ProfileReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProfileReport) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *ProfileReport) GetProfile() *SystemProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SystemProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hardware      *HardwareProfile       `protobuf:"bytes,1,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Software      *SoftwareInventory     `protobuf:"bytes,2,opt,name=software,proto3" json:"software,omitempty"`
	Services      []*ServiceInfo         `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProfile) Reset() {
	*x = SystemProfile{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProfile) ProtoMessage() {}

func (x *SystemProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProfile.ProtoReflect.Descriptor instead.
func (*SystemProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{11}
}

func (x *SystemProfile) GetHardware() *HardwareProfile {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *SystemProfile) GetSoftware() *SoftwareInventory {
	if x != nil {
		return x.Software
	}
	return nil
}

func (x *SystemProfile) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type HardwareProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuModel           string                 `protobuf:"bytes,1,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores           int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads         int32                  `protobuf:"varint,3,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	RamBytes           int64                  `protobuf:"varint,4,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Disks              []*DiskInfo            `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Gpus               []*GPUInfo             `protobuf:"bytes,6,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Nics               []*NICInfo             `protobuf:"bytes,7,rep,name=nics,proto3" json:"nics,omitempty"`
	BiosVersion        string                 `protobuf:"bytes,8,opt,name=bios_version,json=biosVersion,proto3" json:"bios_version,omitempty"`
	SystemManufacturer string                 `protobuf:"bytes,9,opt,name=system_manufacturer,json=systemManufacturer,proto3" json:"system_manufacturer,omitempty"`
	SystemModel        string                 `protobuf:"bytes,10,opt,name=system_model,json=systemModel,proto3" json:"system_model,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,11,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HardwareProfile) Reset() {
	*x = HardwareProfile{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareProfile) ProtoMessage() {}

func (x *HardwareProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareProfile.ProtoReflect.Descriptor instead.
func (*HardwareProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{12}
}

func (x *HardwareProfile) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareProfile) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HardwareProfile) GetCpuThreads() int32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *HardwareProfile) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *HardwareProfile) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HardwareProfile) GetGpus() []*GPUInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareProfile) GetNics() []*NICInfo {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *HardwareProfile) GetBiosVersion() string {
	if x != nil {
		return x.BiosVersion
	}
	return ""
}

func (x *HardwareProfile) GetSystemManufacturer() string {
	if x != nil {
		return x.SystemManufacturer
	}
	return ""
}

func (x *HardwareProfile) GetSystemModel() string {
	if x != nil {
		return x.SystemModel
	}
	return ""
}

func (x *HardwareProfile) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DiskType      string                 `protobuf:"bytes,3,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"` // SSD, HDD, NVMe
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{13}
}

func (x *DiskInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DiskInfo) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *DiskInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	VramBytes     int64                  `protobuf:"varint,2,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{14}
}

func (x *GPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUInfo) GetVramBytes() int64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

type NICInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SpeedMbps     int64                  `protobuf:"varint,2,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	NicType       string                 `protobuf:"bytes,4,opt,name=nic_type,json=nicType,proto3" json:"nic_type,omitempty"` // ethernet, wifi, virtual
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NICInfo) Reset() {
	*x = NICInfo{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NICInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NICInfo) ProtoMessage() {}

func (x *NICInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NICInfo.ProtoReflect.Descriptor instead.
func (*NICInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{15}
}

func (x *NICInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NICInfo) GetSpeedMbps() int64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *NICInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NICInfo) GetNicType() string {
	if x != nil {
		return x.NicType
	}
	return ""
}

type SoftwareInventory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OsName           string                 `protobuf:"bytes,1,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion        string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsBuild          string                 `protobuf:"bytes,3,opt,name=os_build,json=osBuild,proto3" json:"os_build,omitempty"`
	Packages         []*InstalledPackage    `protobuf:"bytes,4,rep,name=packages,proto3" json:"packages,omitempty"`
	DockerContainers []*DockerContainer     `protobuf:"bytes,5,rep,name=docker_containers,json=dockerContainers,proto3" json:"docker_containers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SoftwareInventory) Reset() {
	*x = SoftwareInventory{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareInventory) ProtoMessage() {}

func (x *SoftwareInventory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareInventory.ProtoReflect.Descriptor instead.
func (*SoftwareInventory) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{16}
}

func (x *SoftwareInventory) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *SoftwareInventory) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SoftwareInventory) GetOsBuild() string {
	if x != nil {
		return x.OsBuild
	}
	return ""
}

func (x *SoftwareInventory) GetPackages() []*InstalledPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *SoftwareInventory) GetDockerContainers() []*DockerContainer {
	if x != nil {
		return x.DockerContainers
	}
	return nil
}

type InstalledPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	InstallDate   string                 `protobuf:"bytes,4,opt,name=install_date,json=installDate,proto3" json:"install_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledPackage) Reset() {
	*x = InstalledPackage{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPackage) ProtoMessage() {}

func (x *InstalledPackage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPackage.ProtoReflect.Descriptor instead.
func (*InstalledPackage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{17}
}

func (x *InstalledPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPackage) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *InstalledPackage) GetInstallDate() string {
	if x != nil {
		return x.InstallDate
	}
	return ""
}

type DockerContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerContainer) Reset() {
	*x = DockerContainer{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerContainer) ProtoMessage() {}

func (x *DockerContainer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerContainer.ProtoReflect.Descriptor instead.
func (*DockerContainer) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{18}
}

func (x *DockerContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DockerContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DockerContainer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        // running, stopped, failed
	StartType     string                 `protobuf:"bytes,4,opt,name=start_type,json=startType,proto3" json:"start_type,omitempty"` // auto, manual, disabled
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Ports         []int32                `protobuf:"varint,7,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_api_proto_v1_scout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scout_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetStartType() string {
	if x != nil {
		return x.StartType
	}
	return ""
}

func (x *ServiceInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ServiceInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ServiceInfo) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_api_proto_v1_scout_proto protoreflect.FileDescriptor

const file_api_proto_v1_scout_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/scout.proto\x12\fsubnetree.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n" +
	"\x0eCheckInRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x125\n" +
	"\ametrics\x18\x05 \x01(\v2\x1b.subnetree.v1.SystemMetricsR\ametrics\x12#\n" +
	"\rproto_version\x18\x06 \x01(\rR\fprotoVersion\x12!\n" +
	"\fenroll_token\x18\a \x01(\tR\venrollToken\x12/\n" +
	"\x13certificate_request\x18\b \x01(\fR\x12certificateRequest\"\xac\x03\n" +
	"\x0fCheckInResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x124\n" +
	"\x16check_interval_seconds\x18\x02 \x01(\x05R\x14checkIntervalSeconds\x12)\n" +
	"\x10pending_commands\x18\x03 \x03(\tR\x0fpendingCommands\x12B\n" +
	"\x0eversion_status\x18\x04 \x01(\x0e2\x1b.subnetree.v1.VersionStatusR\rversionStatus\x12%\n" +
	"\x0eserver_version\x18\x05 \x01(\tR\rserverVersion\x12'\n" +
	"\x0fupgrade_message\x18\x06 \x01(\tR\x0eupgradeMessage\x12*\n" +
	"\x11assigned_agent_id\x18\a \x01(\tR\x0fassignedAgentId\x12-\n" +
	"\x12signed_certificate\x18\b \x01(\fR\x11signedCertificate\x12%\n" +
	"\x0eca_certificate\x18\t \x01(\fR\rcaCertificate\"\xe7\x02\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x01R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x01R\x10memoryTotalBytes\x12.\n" +
	"\x05disks\x18\x05 \x03(\v2\x18.subnetree.v1.DiskMetricR\x05disks\x127\n" +
	"\bnetworks\x18\x06 \x03(\v2\x1b.subnetree.v1.NetworkMetricR\bnetworks\x12K\n" +
	"\x0fcontainer_stats\x18\a \x03(\v2\".subnetree.v1.DockerContainerStatsR\x0econtainerStats\"\x8c\x01\n" +
	"\n" +
	"DiskMetric\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x01R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x01R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x01R\tfreeBytes\"t\n" +
	"\rNetworkMetric\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x01R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x01R\tbytesRecv\"\xaf\x03\n" +
	"\x14DockerContainerStats\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12,\n" +
	"\x12memory_usage_bytes\x18\x04 \x01(\x04R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x04R\x10memoryLimitBytes\x12%\n" +
	"\x0ememory_percent\x18\x06 \x01(\x01R\rmemoryPercent\x12(\n" +
	"\x10network_rx_bytes\x18\a \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\b \x01(\x04R\x0enetworkTxBytes\x12(\n" +
	"\x10block_read_bytes\x18\t \x01(\x04R\x0eblockReadBytes\x12*\n" +
	"\x11block_write_bytes\x18\n" +
	" \x01(\x04R\x0fblockWriteBytes\x12\x12\n" +
	"\x04pids\x18\v \x01(\rR\x04pids\"\x7f\n" +
	"\rMetricsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x125\n" +
	"\ametrics\x18\x03 \x01(\v2\x1b.subnetree.v1.SystemMetricsR\ametrics\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"x\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa0\x01\n" +
	"\rProfileReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12=\n" +
	"\fcollected_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x125\n" +
	"\aprofile\x18\x03 \x01(\v2\x1b.subnetree.v1.SystemProfileR\aprofile\"\xbe\x01\n" +
	"\rSystemProfile\x129\n" +
	"\bhardware\x18\x01 \x01(\v2\x1d.subnetree.v1.HardwareProfileR\bhardware\x12;\n" +
	"\bsoftware\x18\x02 \x01(\v2\x1f.subnetree.v1.SoftwareInventoryR\bsoftware\x125\n" +
	"\bservices\x18\x03 \x03(\v2\x19.subnetree.v1.ServiceInfoR\bservices\"\xa9\x03\n" +
	"\x0fHardwareProfile\x12\x1b\n" +
	"\tcpu_model\x18\x01 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\x03 \x01(\x05R\n" +
	"cpuThreads\x12\x1b\n" +
	"\tram_bytes\x18\x04 \x01(\x03R\bramBytes\x12,\n" +
	"\x05disks\x18\x05 \x03(\v2\x16.subnetree.v1.DiskInfoR\x05disks\x12)\n" +
	"\x04gpus\x18\x06 \x03(\v2\x15.subnetree.v1.GPUInfoR\x04gpus\x12)\n" +
	"\x04nics\x18\a \x03(\v2\x15.subnetree.v1.NICInfoR\x04nics\x12!\n" +
	"\fbios_version\x18\b \x01(\tR\vbiosVersion\x12/\n" +
	"\x13system_manufacturer\x18\t \x01(\tR\x12systemManufacturer\x12!\n" +
	"\fsystem_model\x18\n" +
	" \x01(\tR\vsystemModel\x12#\n" +
	"\rserial_number\x18\v \x01(\tR\fserialNumber\"\x88\x01\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tdisk_type\x18\x03 \x01(\tR\bdiskType\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\"e\n" +
	"\aGPUInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\x02 \x01(\x03R\tvramBytes\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\"x\n" +
	"\aNICInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x02 \x01(\x03R\tspeedMbps\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bnic_type\x18\x04 \x01(\tR\anicType\"\xee\x01\n" +
	"\x11SoftwareInventory\x12\x17\n" +
	"\aos_name\x18\x01 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x19\n" +
	"\bos_build\x18\x03 \x01(\tR\aosBuild\x12:\n" +
	"\bpackages\x18\x04 \x03(\v2\x1e.subnetree.v1.InstalledPackageR\bpackages\x12J\n" +
	"\x11docker_containers\x18\x05 \x03(\v2\x1d.subnetree.v1.DockerContainerR\x10dockerContainers\"\x81\x01\n" +
	"\x10InstalledPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12!\n" +
	"\finstall_date\x18\x04 \x01(\tR\vinstallDate\"v\n" +
	"\x0fDockerContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xd5\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_type\x18\x04 \x01(\tR\tstartType\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x03R\vmemoryBytes\x12\x14\n" +
	"\x05ports\x18\a \x03(\x05R\x05ports*k\n" +
	"\rVersionStatus\x12\x0e\n" +
	"\n" +
	"VERSION_OK\x10\x00\x12\x16\n" +
	"\x12VERSION_DEPRECATED\x10\x01\x12\x14\n" +
	"\x10VERSION_REJECTED\x10\x02\x12\x1c\n" +
	"\x18VERSION_UPDATE_AVAILABLE\x10\x032\xa5\x02\n" +
	"\fScoutService\x12F\n" +
	"\aCheckIn\x12\x1c.subnetree.v1.CheckInRequest\x1a\x1d.subnetree.v1.CheckInResponse\x12A\n" +
	"\rReportMetrics\x12\x1b.subnetree.v1.MetricsReport\x1a\x11.subnetree.v1.Ack(\x01\x12I\n" +
	"\rCommandStream\x12\x1d.subnetree.v1.CommandResponse\x1a\x15.subnetree.v1.Command(\x010\x01\x12?\n" +
	"\rReportProfile\x12\x1b.subnetree.v1.ProfileReport\x1a\x11.subnetree.v1.AckB4Z2github.com/HerbHall/subnetree/api/proto/v1;scoutpbb\x06proto3"

var (
	file_api_proto_v1_scout_proto_rawDescOnce sync.Once
	file_api_proto_v1_scout_proto_rawDescData []byte
)

func file_api_proto_v1_scout_proto_rawDescGZIP() []byte {
	file_api_proto_v1_scout_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_scout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_scout_proto_rawDesc), len(file_api_proto_v1_scout_proto_rawDesc)))
	})
	return file_api_proto_v1_scout_proto_rawDescData
}

var file_api_proto_v1_scout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_scout_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_v1_scout_proto_goTypes = []any{
	(VersionStatus)(0),            // 0: subnetree.v1.VersionStatus
	(*CheckInRequest)(nil),        // 1: subnetree.v1.CheckInRequest
	(*CheckInResponse)(nil),       // 2: subnetree.v1.CheckInResponse
	(*SystemMetrics)(nil),         // 3: subnetree.v1.SystemMetrics
	(*DiskMetric)(nil),            // 4: subnetree.v1.DiskMetric
	(*NetworkMetric)(nil),         // 5: subnetree.v1.NetworkMetric
	(*DockerContainerStats)(nil),  // 6: subnetree.v1.DockerContainerStats
	(*MetricsReport)(nil),         // 7: subnetree.v1.MetricsReport
	(*Ack)(nil),                   // 8: subnetree.v1.Ack
	(*Command)(nil),               // 9: subnetree.v1.Command
	(*CommandResponse)(nil),       // 10: subnetree.v1.CommandResponse
	(*ProfileReport)(nil),         // 11: subnetree.v1.ProfileReport
	(*SystemProfile)(nil),         // 12: subnetree.v1.SystemProfile
	(*HardwareProfile)(nil),       // 13: subnetree.v1.HardwareProfile
	(*DiskInfo)(nil),              // 14: subnetree.v1.DiskInfo
	(*GPUInfo)(nil),               // 15: subnetree.v1.GPUInfo
	(*NICInfo)(nil),               // 16: subnetree.v1.NICInfo
	(*SoftwareInventory)(nil),     // 17: subnetree.v1.SoftwareInventory
	(*InstalledPackage)(nil),      // 18: subnetree.v1.InstalledPackage
	(*DockerContainer)(nil),       // 19: subnetree.v1.DockerContainer
	(*ServiceInfo)(nil),           // 20: subnetree.v1.ServiceInfo
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_api_proto_v1_scout_proto_depIdxs = []int32{
	3,  // 0: subnetree.v1.CheckInRequest.metrics:type_name -> subnetree.v1.SystemMetrics
	0,  // 1: subnetree.v1.CheckInResponse.version_status:type_name -> subnetree.v1.VersionStatus
	4,  // 2: subnetree.v1.SystemMetrics.disks:type_name -> subnetree.v1.DiskMetric
	5,  // 3: subnetree.v1.SystemMetrics.networks:type_name -> subnetree.v1.NetworkMetric
	6,  // 4: subnetree.v1.SystemMetrics.container_stats:type_name -> subnetree.v1.DockerContainerStats
	3,  // 5: subnetree.v1.MetricsReport.metrics:type_name -> subnetree.v1.SystemMetrics
	21, // 6: subnetree.v1.ProfileReport.collected_at:type_name -> google.protobuf.Timestamp
	12, // 7: subnetree.v1.ProfileReport.profile:type_name -> subnetree.v1.SystemProfile
	13, // 8: subnetree.v1.SystemProfile.hardware:type_name -> subnetree.v1.HardwareProfile
	17, // 9: subnetree.v1.SystemProfile.software:type_name -> subnetree.v1.SoftwareInventory
	20, // 10: subnetree.v1.SystemProfile.services:type_name -> subnetree.v1.ServiceInfo
	14, // 11: subnetree.v1.HardwareProfile.disks:type_name -> subnetree.v1.DiskInfo
	15, // 12: subnetree.v1.HardwareProfile.gpus:type_name -> subnetree.v1.GPUInfo
	16, // 13: subnetree.v1.HardwareProfile.nics:type_name -> subnetree.v1.NICInfo
	18, // 14: subnetree.v1.SoftwareInventory.packages:type_name -> subnetree.v1.InstalledPackage
	19, // 15: subnetree.v1.SoftwareInventory.docker_containers:type_name -> subnetree.v1.DockerContainer
	1,  // 16: subnetree.v1.ScoutService.CheckIn:input_type -> subnetree.v1.CheckInRequest
	7,  // 17: subnetree.v1.ScoutService.ReportMetrics:input_type -> subnetree.v1.MetricsReport
	10, // 18: subnetree.v1.ScoutService.CommandStream:input_type -> subnetree.v1.CommandResponse
	11, // 19: subnetree.v1.ScoutService.ReportProfile:input_type -> subnetree.v1.ProfileReport
	2,  // 20: subnetree.v1.ScoutService.CheckIn:output_type -> subnetree.v1.CheckInResponse
	8,  // 21: subnetree.v1.ScoutService.ReportMetrics:output_type -> subnetree.v1.Ack
	9,  // 22: subnetree.v1.ScoutService.CommandStream:output_type -> subnetree.v1.Command
	8,  // 23: subnetree.v1.ScoutService.ReportProfile:output_type -> subnetree.v1.Ack
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_v1_scout_proto_init() }
func file_api_proto_v1_scout_proto_init() {
	if File_api_proto_v1_scout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_scout_proto_rawDesc), len(file_api_proto_v1_scout_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_scout_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_scout_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_scout_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_scout_proto_msgTypes,
	}.Build()
	File_api_proto_v1_scout_proto = out.File
	file_api_proto_v1_scout_proto_goTypes = nil
	file_api_proto_v1_scout_proto_depIdxs = nil
}
